[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "synde"
version = "0.1.0"
authors = [
    {name="Tieu Long Phan", email="tieu@bioinf.uni-leipzig.de"}
]
description = "Utility for reaction modeling using graph grammar"
readme = "README.md"
long-description = {file = "CHANGELOG.md"}
long-description-content-type = "text/markdown"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "rdkit>=2025.3.1",
    "numpy>=2.2.0",
    "synkit>=1.5.0",
]

[project.optional-dependencies]
all = ["numpy>=2.2.0", "pandas>=1.5.3"]
docs = [
  "sphinx>=6.0",
  "sphinx-rtd-theme",
  "sphinxcontrib-bibtex",
]

[project.urls]
homepage = "https://github.com/tuyetminhphan/SynDE"
source = "https://github.com/tuyetminhphan/SynDE"
issues = "https://github.com/tuyetminhphan/SynDE/issues"
documentation = "https://synde.readthedocs.io/en/latest/"
